import React, { useState } from 'react';
import { generateInspirationImage } from '../services/geminiService';
import { Image as ImageIcon, Download, Sparkles, Wand2 } from 'lucide-react';

const InspirationGen: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [imageSrc, setImageSrc] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    setLoading(true);
    setImageSrc(null);
    try {
      const result = await generateInspirationImage(prompt);
      if (result) {
        setImageSrc(result);
      } else {
        alert("Could not generate image. Please try a different prompt.");
      }
    } catch (e) {
      console.error(e);
      alert("Error generating image.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-8">
      <div className="text-center max-w-2xl mx-auto py-8">
        <div className="inline-flex items-center justify-center p-3 bg-brand-50 text-brand-600 rounded-full mb-4">
           <Wand2 size={24} />
        </div>
        <h2 className="text-4xl font-serif font-bold text-gray-800 mb-3">Dream It. See It.</h2>
        <p className="text-gray-500 text-lg leading-relaxed">
          Describe your perfect wedding detail—be it a cake, dress, or venue—and watch our AI visualize it for you instantly.
        </p>
      </div>

      <div className="bg-white p-2 rounded-2xl shadow-soft border border-gray-100 max-w-3xl mx-auto">
        <div className="flex flex-col md:flex-row gap-2">
          <input
            type="text"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="e.g., A three-tier cake with gold leaf and blush roses..."
            className="flex-1 rounded-xl border-transparent focus:border-transparent focus:ring-0 p-4 bg-transparent text-gray-800 placeholder-gray-400"
          />
          <button
            onClick={handleGenerate}
            disabled={loading || !prompt.trim()}
            className="bg-brand-600 hover:bg-brand-700 text-white px-8 py-3 rounded-xl font-bold flex items-center justify-center gap-2 transition-all shadow-lg shadow-brand-200 disabled:opacity-50 disabled:shadow-none"
          >
            {loading ? <Sparkles className="animate-spin" size={20} /> : <Sparkles size={20} />}
            {loading ? 'Creating...' : 'Visualize'}
          </button>
        </div>
      </div>

      <div className="flex justify-center mt-8 pb-10">
        {loading ? (
           <div className="w-full max-w-2xl aspect-video bg-white rounded-3xl shadow-soft border border-gray-100 flex items-center justify-center">
             <div className="text-center">
                <div className="relative w-20 h-20 mx-auto mb-4">
                  <div className="absolute inset-0 bg-brand-100 rounded-full animate-ping opacity-75"></div>
                  <div className="relative bg-white p-4 rounded-full shadow-sm">
                    <Sparkles size={32} className="text-brand-500 animate-pulse" />
                  </div>
                </div>
                <p className="text-gray-500 font-medium">Generating your vision...</p>
                <p className="text-xs text-gray-400 mt-2">This may take a few seconds</p>
             </div>
           </div>
        ) : imageSrc ? (
          <div className="relative group max-w-4xl w-full">
            <div className="absolute -inset-1 bg-gradient-to-r from-brand-300 to-purple-300 rounded-[2rem] blur opacity-25 group-hover:opacity-50 transition duration-1000"></div>
            <div className="relative">
              <img 
                src={imageSrc} 
                alt="Generated Inspiration" 
                className="rounded-3xl shadow-2xl border-4 border-white w-full"
              />
              <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity rounded-3xl flex items-center justify-center backdrop-blur-[2px]">
                  <a 
                    href={imageSrc} 
                    download={`wedding-inspo-${Date.now()}.png`}
                    className="bg-white hover:scale-110 text-brand-600 px-6 py-3 rounded-full shadow-xl font-bold flex items-center gap-2 transition-all"
                  >
                    <Download size={20} />
                    Download Image
                  </a>
              </div>
            </div>
            <p className="text-center text-xs text-gray-400 mt-4 font-medium uppercase tracking-widest">Generated by Gemini AI</p>
          </div>
        ) : (
          <div className="w-full max-w-2xl aspect-video bg-gray-50 rounded-3xl border-2 border-dashed border-gray-200 flex items-center justify-center group hover:border-brand-200 hover:bg-brand-50/20 transition-colors">
            <div className="text-center p-8">
                <div className="bg-white p-4 rounded-full shadow-sm inline-block mb-4 group-hover:scale-110 transition-transform">
                  <ImageIcon size={32} className="text-gray-300 group-hover:text-brand-400" />
                </div>
                <h3 className="text-gray-500 font-bold">No Image Generated Yet</h3>
                <p className="text-sm text-gray-400 mt-1 max-w-xs mx-auto">Enter a detailed prompt above to start building your inspiration board.</p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default InspirationGen;